name: Check Python Version

on:
  push:
    branches:
      - main

jobs:
  check_python_version:
    runs-on: ubuntu-latest
    steps:
       - name: Install Python
         uses: actions/setup-python@v4
         with:
           python-version: 3.11
       
       - name: Pip UPdate
         run: python -m pip install --upgrade pip

       - name: Print python version
         run: python --version
